services:
  bookstore:
    image: mysql:8.3.0
    container_name: bookstore-mysql
    ports:
      - "3326:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql:/var/lib/mysql